### PR TITLE
Fix/location date format

### PR DESCRIPTION
**Pull request by KochTobi**
Use the ISO_8601_DATETIME_FORMAT instead of a custom minute resolution

``"yyyy-MM-dd'T'HH:mm'Z'"`` -> ``"yyyy-MM-dd'T'HH:mm:ss'Z'"``

### CODE REVIEW

**Review by sven1103 — DISMISSED** [review]
Nice!

**Comment by sven1103** [comment]
Though you need to change the base branch imo

**Comment by KochTobi** [comment]
Yes there was some movement in the last days.

**Comment by jenniferboedker** [comment]
@KochTobi if this is an important solution maybe it would be good to document the issue (in an issue) and mention the solution so we can delete this branch.

**Comment by KochTobi** [comment]
We need to conform with ISO standards otherwise REST calls with this object are hell!

**Pull request closed without merging**
