### PR TITLE
Add optional property to link an project in the offer

### PR DESCRIPTION
**Pull request by sven1103**

### CODE REVIEW

**Comment by sven1103** [comment]
[Extend the offer and offer overview DTO with a reference to the project](https://trello.com/c/Iy4KKSVv/618-extend-the-offer-and-offer-overview-dto-with-a-reference-to-the-project)

**Comment by sven1103** [comment]
supports https://github.com/qbicsoftware/offer-manager-2-portlet/issues/277

**Review by jenniferboedker — APPROVED** [review]
Looks good!

**Review by jenniferboedker — COMMENTED** [review]
Looks good. Though I think it would also make sense to introduce the new field to the `Converter` so the information of the DTOs do not get lost.

**Comment by jenniferboedker** [comment]
> Looks good. Though I think it would also make sense to introduce the new field to the `Converter` so the information of the DTOs do not get lost.

Forget that.. I mixed up your PRs this was meant for the PR in the offer manager 🙈

**Pull request merged**
